#!/bin/bash --login


### Run installers 
# Set all files in auto to executable
chmod +x -R ./auto/*
#
# Ruby and Python
./auto/install/rvm 
./auto/install/pyenv 
#
# Zsh, Vim & Tmux
./auto/install/zsh
./auto/install/vim
./auto/install/tmux
