" General Vim settings
    syntax on
    let mapleader=","
    set autoindent
    set tabstop=4
    set shiftwidth=4
    set dir=/tmp/

    autocmd Filetype html setlocal sw=2 expandtab
    autocmd Filetype javascript setlocal sw=2 expandtab

    set hlsearch

" Disable tmux navigator when zooming the Vim pane
    let g:tmux_navigator_disable_when_zoomed = 1

    " Line Numbers
    set number
    set norelativenumber 
    nnoremap <C-n> :set relativenumber!<CR>

" Language Specific
    " Tabs
        so ~/dotfiles/vim/sleuth.vim

    " Typescript
        autocmd BufNewFile,BufRead *.ts set syntax=javascript
        autocmd BufNewFile,BufRead *.tsx set syntax=javascript

    " Markup
        inoremap <leader>< <esc>I<<esc>A><esc>yypa/<esc>O<tab>


" File and Window Management 
    set splitbelow
    set splitright
    
    inoremap <leader>w <Esc>:w<CR>
    nnoremap <leader>w :w<CR>

    inoremap <leader>q <ESC>:q<CR>
    nnoremap <leader>q :q<CR>

    inoremap <leader>x <ESC>:x<CR>
    nnoremap <leader>x :x<CR>

    nnoremap <leader>e :Explore<CR>
    nnoremap <leader>r :Rex<CR>
    nnoremap <leader>v :Vex!<CR>
    nnoremap <leader>s :Sex<CR>

" Return to the same line you left off at
    augroup line_return
        au!
        au BufReadPost *
            \ if line("'\"") > 0 && line("'\"") <= line("$") |
            \   execute 'normal! g`"zvzz' |
            \ endif
    augroup END

" Auto load
    " Triger `autoread` when files changes on disk
    " https://unix.stackexchange.com/questions/149209/refresh-changed-content-of-file-opened-in-vim/383044#383044
    " https://vi.stackexchange.com/questions/13692/prevent-focusgained-autocmd-running-in-command-line-editing-mode
    autocmd FocusGained,BufEnter,CursorHold,CursorHoldI * if mode() != 'c' | checktime | endif
    set autoread
    " Notification after file change
    " https://vi.stackexchange.com/questions/13091/autocmd-event-for-autoread
    autocmd FileChangedShellPost *
      \ echohl WarningMsg | echo "File changed on disk. Buffer reloaded." | echohl None

filetype plugin indent on

execute pathogen#infect()

