#!/bin/bash

VERSION=2.8
if [[ "$( tmux -V | cut -d ' ' -f 2 )" = "$VERSION" ]]; then
  echo "Tmux already install with desired version of $VERSION"
  exit
else
  back=$(pwd)

  mkdir -p ~/.tmux_tmp_install && cd ~/.tmux_tmp_install

  git clone https://github.com/tmux/tmux.git && cd tmux

  git checkout $VERSION

  ./autogen.sh
  ./configure && make

  sudo apt remove tmux -y && sudo mv tmux /usr/bin/tmux

  cd $back && rm -rf ~/.tmux_tmp_install
fi
